### ISSUE TITLE
Macros do not respect multiple playbacks accurately (ex. 2@f)

### ISSUE THREAD

**Issue by fritogotlayed** [JunSuzukiJapan/atom-keyboard-macros-vim#14]
### Symptom
Macros do not respect multiple playbacks accurately (ex. 2@f)

### Steps To Reproduce
* Start one line 1 on the left most blank space
* Enter following key sequence:
  * q j J l c w name [esc] J l c w location [esc] J J J J l l l x i [enter] [esc] q

### Input Data
```
  // Already formatted data here
  {
    a: "name 1",
    b: {
        x: 1,
        y: 1
    }
}, {
    a: "name 2",
    b: {
        x: 2,
        y: 2
    }
}, {
  // More data here ...
```

### Expected Result
```
  { name: "name 1", location: { x: 1, y: 1 } },
  { name: "name 2", location: { x: 2, y: 2 } },
  {
```

### Actual Result
```
  { a: "name 1", name: { location: 1, y: 1 } }, {a: 
    "name 2", 
    b: { 
         x: 2,
         y: 2
    }
 }, {
```

### Tested Versions
* Atom Editor: 1.14.3 ia32
* atom-keyboard-macros-vim: 0.1.6

NOTE: If there's any more information I can provide please let me know and I will gather it for you.

**Comment by mayask** [comment]
Duplicate https://github.com/JunSuzukiJapan/atom-keyboard-macros-vim/issues/9
