### ISSUE TITLE
end recording macro in insert mode

### ISSUE THREAD

**Issue by inBrink** [JunSuzukiJapan/atom-keyboard-macros-vim#2]
Need to add hotkey to end recording macro when in insert mode ([article link](https://www.quora.com/How-do-you-stop-recording-a-Vim-macro-when-in-insert-mode))

**Comment by JunSuzukiJapan** [comment]
Please write as below in your 'keymap.cson' file.

```
'atom-text-editor.vim-mode.insert-mode':
  'cmd-alt-e': 'atom-keyboard-macros-vim:toggle_record_macro_vim'
```

Of course, the keystroke may be the your favorite.

**Comment by inBrink** [comment]
Thanks a lot.

**Comment by JunSuzukiJapan** [comment]
Thank you.
